### ISSUE TITLE
curl request

### ISSUE THREAD

**Issue by BinaryJim** [felicianotech/docker-hugo#34]
Would it be possible to add curl (not cURL or libcurl "CURL") to this image? 

Part of my CI is to purge CloudFlare cache using their API, which requires curl, so this addition would be great.

Thanks

**Comment by felicianotech** [comment]
The referenced PR should fix this correct?

If so, I can merge it, and I'll update the last few main release tags for Hugo. That would be Hugo v0.32.4, v0.31.1, and Hugo v0.30.2.

**Comment by BinaryJim** [comment]
Yup, that PR looks like it’ll do the trick - if you can merge that’ll be great. 

Manny thanks

**Comment by felicianotech** [comment]
Okay `curl` is now available in the following tags:

- cibuilds/hugo:latest
- cibuilds/hugo:0.32
- cibuilds/hugo:0.32.4
- cibuilds/hugo:0.31
- cibuilds/hugo:0.31.1
- cibuilds/hugo:0.30
- cibuilds/hugo:0.30.2

and any future Hugo release from here on out. Enjoy.

**Comment by BinaryJim** [comment]
Top man! 

Thanks for implementing this so quickly and your efforts / contribution to the community to date, really appreciated.
