### ISSUE TITLE
Add aws cli 

### ISSUE THREAD

**Issue by albush** [felicianotech/docker-hugo#45]
Would you consider adding commands to install aws cli to make it easier to deploy straight to S3?

**Comment by felicianotech** [comment]
Not to this image no but that's what I created the AWS image for: https://github.com/cibuilds/aws

On CircleCI for example, you can build the site and test in one job, and have a deployment job that uses the AWS image.

Does that make sense?

**Comment by albush** [comment]
That makes sense, I think. I'm still digging into the Circle CI 2.0 documentation, but I think I can make it work. 

Thanks for the fast response.

**Comment by felicianotech** [comment]
No problem. I'm a Developer Evangelist at CircleCI so if you need any help or have questions, I'm FelicianoTech on Twitter and on CircleCI Discuss.
